### PR TITLE
Refactor Runner to Backend

### PR DESCRIPTION
**Pull request by rhit-windsors**

### CODE REVIEW

**Comment by rhit-windsors** [comment]
I would like everyone to review this before merge.

**Comment by rhit-windsors** [comment]
The pylint updated, the config broke it. I had to change the config file to fix it.

**Review by rhit-johnsoz2 — APPROVED** [review]
Looks good to me!

**Review by rhit-toftnebj — APPROVED** [review]

**Review by bveal52 — APPROVED** [review]
Looks good, nice work

**Pull request merged**
